version: "3.7"

services:

    ## Image
    bff_lounge_front:
        build:
            args:
                user: ezequieldhonatan
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - microservices

    ## Nginx
    nginx:
        image: nginx:alpine
        restart: unless-stopped
        ports:
            - 8010:80
        volumes:
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks:
            - microservices

networks:
    microservices:
        driver: bridge
